[project]
name = "reconstruct-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "pillow>=12.3.0",
]

[project.scripts]
reconstruct-ai = "reconstruct_ai:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
